### ISSUE TITLE
Request: Moderation commands

### ISSUE THREAD

**Issue by MirageAegis** [EMWFabianSales/Ramiel#3]
As a moderator, I want a way to easily moderate a server, so I can do my job more effectively.

**Acceptance criteria**
- Ramie shall allow moderators to kick users and optionally provide a reason.
- Ramie shall allow moderators to ban users and optionally provide a reason.
- Ramie shall allow moderators to time users out and optionally provide a reason.
- Ramie shall allow moderators to clear messages in bulk.

**Comment by EMWFabianSales** [comment]
all features added and ready for next update
